# @format

name: Build and release

on:
  workflow_call:
    inputs:
      image_dir:
        required: true
        type: string
        description: "The path to the docker file for example './<dir>/<dir>/Dockerfile' "

defaults:
  run:
    working-directory: base_image

jobs:
  build_base:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: echo ${{ inputs.image_dir }}
  release_base:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          make
          make push
