# @format

name: Build and release

on:
  workflow_call:
    inputs:
      image_dir:
        required: true
        type: string
        description: "The path to the docker file for example './<dir>/<dir>/Dockerfile' "
      vars:
        required: false
        type: string
        description: "The path to the docker file for example './<dir>/<dir>/Dockerfile' "

# defaults:
#   run:
#     working-directory: ${{ inputs.image_dir }}/

jobs:
  build_image:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.image_dir }}
    permissions:
    # so that one does not push any image that is not ready 
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: make build ${{ inputs.vars }}

  release_image:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.image_dir }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        run: |
          make build ${{ inputs.vars }}
          make push
