# @format

# Workflow name displayed in GitHub Actions
name: k8 image pipeline

# Triggers that initiate the workflow execution
on:
  workflow_dispatch: # Manual triggering from Actions tab
  pull_request:
    # Runs on pull requests targeting the main branch (uncomment for specific paths)
    paths:
      - 'labs/k8_lab/**'
    branches: [main]
  push:
    # Runs on pushes to the main branch (uncomment for specific paths)
    paths:
      - 'labs/k8_lab/**'
    branches: [main]

# Define jobs within the workflow
jobs:
  build-base: # Job name
    uses: ./.github/workflows/base_image.yml # Reference reusable workflow
    with:
      image-dir: base_image # Argument passed to the reusable workflow
    secrets: inherit # Inherit secrets from the main workflow

  build-k8: # Job name
    uses: ./.github/workflows/base_image.yml # Reference reusable workflow
    with:
      image-dir: labs/k8_lab # Argument passed to the reusable workflow
    secrets: inherit # Inherit secrets from the main workflow
