# @format

# Workflow name displayed in GitHub Actions
name: vm image pipelime
# Triggers that initiate the workflow execution
on:
  workflow_dispatch: # Manual triggering from Actions tab
  pull_request:
    # Runs on pull requests targeting the main branch (uncomment for specific paths)
    paths:
      - 'labs/vm_lab/**'
    branches: [main]
  push:
    # Runs on pushes to the main branch (uncomment for specific paths)
    paths:
      - 'labs/vm_lab/**'
    branches: [main]

# Define jobs within the workflow
jobs:
  build-base: # Job name
    uses: ./.github/workflows/base_image.yml # Reference reusable workflow
    permissions:
      contents: read
      packages: write
    with:
      image_dir: base_image # Argument passed to the reusable workflow
    secrets: inherit # Inherit secrets from the main workflow

  build-vm: # Job name
    needs:  build-base
    uses: ./.github/workflows/base_image.yml # Reference reusable workflow
    permissions:
      contents: read
      packages: write
    with:
      image_dir: labs/vm_lab # Argument passed to the reusable workflow
    secrets: inherit # Inherit secrets from the main workflow
